AllCops:
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - examples/**/*

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  CountComments: false
  Max: 25

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
